//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Services {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Services.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ComissionIsExit.
        /// </summary>
        internal static string ComissionIsExit {
            get {
                return ResourceManager.GetString("ComissionIsExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comission Sharing Model already exist.
        /// </summary>
        internal static string ComissionModelIsExit {
            get {
                return ResourceManager.GetString("ComissionModelIsExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We are facing some issue at this moment. Please contact to support team..
        /// </summary>
        internal static string ContactToAdmin {
            get {
                return ResourceManager.GetString("ContactToAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We are Facing some IssueIn while Fatching Onboarding details..
        /// </summary>
        internal static string FacingIssueInFatchingOnboarding {
            get {
                return ResourceManager.GetString("FacingIssueInFatchingOnboarding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First time login, Please change password..
        /// </summary>
        internal static string FirstTimeLoginUserNeedToChangeThePassword {
            get {
                return ResourceManager.GetString("FirstTimeLoginUserNeedToChangeThePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OTP sent successfully.
        /// </summary>
        internal static string ForgotPasswordOTP {
            get {
                return ResourceManager.GetString("ForgotPasswordOTP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid OTP.
        /// </summary>
        internal static string InValidOTP {
            get {
                return ResourceManager.GetString("InValidOTP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can only activate or deactivate user. Provide status 2 to activate and 3 to deactivate..
        /// </summary>
        internal static string InValidStatus {
            get {
                return ResourceManager.GetString("InValidStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid username or password.
        /// </summary>
        internal static string InvalidUserNamePassword {
            get {
                return ResourceManager.GetString("InvalidUserNamePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile number already is in use.
        /// </summary>
        internal static string MobileNumberExist {
            get {
                return ResourceManager.GetString("MobileNumberExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password needs to be change. .
        /// </summary>
        internal static string NeedResetPassword {
            get {
                return ResourceManager.GetString("NeedResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NoLocationFound.
        /// </summary>
        internal static string NoLocationFound {
            get {
                return ResourceManager.GetString("NoLocationFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No sub user found ....
        /// </summary>
        internal static string NoSubUserFound {
            get {
                return ResourceManager.GetString("NoSubUserFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OTP has been expired..
        /// </summary>
        internal static string OTPExpire {
            get {
                return ResourceManager.GetString("OTPExpire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password has been expired. Kindly reset your password..
        /// </summary>
        internal static string PasswordExpired {
            get {
                return ResourceManager.GetString("PasswordExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reportnotfound.
        /// </summary>
        internal static string Reportnotfound {
            get {
                return ResourceManager.GetString("Reportnotfound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password has been reset successfully. .
        /// </summary>
        internal static string ResetPasswordSuccessfully {
            get {
                return ResourceManager.GetString("ResetPasswordSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role Name can not be duplicate.
        /// </summary>
        internal static string RoleAlreadyExists {
            get {
                return ResourceManager.GetString("RoleAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We have noticed Some Onboarding Details Are Pending. Please Continue the same..
        /// </summary>
        internal static string SomeOnboardingDetailsArePending {
            get {
                return ResourceManager.GetString("SomeOnboardingDetailsArePending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We have noticed Some Onboarding Details have Failed. Please Contact Administrator..
        /// </summary>
        internal static string SomeOnboardingDetailsHaveFailed {
            get {
                return ResourceManager.GetString("SomeOnboardingDetailsHaveFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On boarding KYC details are pending.
        /// </summary>
        internal static string SomeOnboardingKYCsArePending {
            get {
                return ResourceManager.GetString("SomeOnboardingKYCsArePending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SomethingWentWrongWhileUpdatingVPA.
        /// </summary>
        internal static string SomethingWentWrongWhileUpdatingVPA {
            get {
                return ResourceManager.GetString("SomethingWentWrongWhileUpdatingVPA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to fetch wallet balance at this moment. Please contact administrator..
        /// </summary>
        internal static string UnableToFetcBalance {
            get {
                return ResourceManager.GetString("UnableToFetcBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UnableToFetcpaymentHistory.
        /// </summary>
        internal static string UnableToFetcpaymentHistory {
            get {
                return ResourceManager.GetString("UnableToFetcpaymentHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User already exist.
        /// </summary>
        internal static string UserAlreadyExist {
            get {
                return ResourceManager.GetString("UserAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Blocked Permanently.
        /// </summary>
        internal static string UserBlockedPermanently {
            get {
                return ResourceManager.GetString("UserBlockedPermanently", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User is deleted.
        /// </summary>
        internal static string UserIsDeleted {
            get {
                return ResourceManager.GetString("UserIsDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User is not active.
        /// </summary>
        internal static string UserIsInActive {
            get {
                return ResourceManager.GetString("UserIsInActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User is locked.
        /// </summary>
        internal static string UserIsIsLocked {
            get {
                return ResourceManager.GetString("UserIsIsLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User haven&apos;t changed password for long time. Please change the password..
        /// </summary>
        internal static string UserNeedToChangeThePassword {
            get {
                return ResourceManager.GetString("UserNeedToChangeThePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User not found.
        /// </summary>
        internal static string UserNotFound {
            get {
                return ResourceManager.GetString("UserNotFound", resourceCulture);
            }
        }
    }
}
